FROM fpco/stack-run
MAINTAINER Avi Knoll <aknoll@atlassian.com>

# Expose the default port required by Micros
EXPOSE 8080

# Install Java
RUN apt-get update && apt-get install -y openjdk-9-jre-headless

# Install static files
COPY snaplets /service/snaplets
COPY resources /service/resources
COPY migrations /service/migrations
ENV FLYWAY_PATH /service/migrations/flyway
COPY static /service/static

# Copy and run binary
ADD build-bin/confluence-pandoc-connect /usr/bin/confluence-pandoc-connect
WORKDIR /service
CMD ["confluence-pandoc-connect", "--access-log=-", "--error-log=stderr", "--port=8080"]
